# Management 
/MG/manager/mglog routine #debugging

/MG/manager/seedWithUUID

# Process List
/MG/processes/realm DarkMatter
/MG/processes/lowenergy true
/MG/processes/optical true
#/MG/processes/opticalOnly true

# Configure Detector
/MG/geometry/detector BACON

# Initialize Geant4 and geometry
/run/initialize

/MG/eventaction/rootschema MCOpticalRun
/MG/eventaction/reportingfrequency 10
/MG/eventaction/rootfilename outputGamma.root

#/MG/io/MCOpticalRun/SetSensitiveIDLabelScheme askGeom
/MG/io/MCOpticalRun/SetSensitiveIDLabelScheme manual
/MG/io/MCOpticalRun/setRunID 001
/MG/io/MCOpticalRun/AddSensitiveVolnameID physicalPMT_0 200
/MG/io/MCOpticalRun/AddSensitiveVolnameID physicalPMT_1 201
/MG/io/MCOpticalRun/AddSensitiveVolnameID Detector 100
/MG/io/MCOpticalRun/AddSensitiveVolnameID argonGasPhysical 101
/MG/io/MCOpticalRun/AddSensitiveVolnameID CryoCan 300
/MG/io/MCOpticalRun/AddSensitiveVolnameID Cryostat 301
/MG/io/MCOpticalRun/AddSensitiveVolnameID CryoWell 302
/MG/io/MCOpticalRun/useTimeWindow true
/MG/io/MCOpticalRun/setTimeWindow 86400 second
/MG/io/MCOpticalRun/setNSteps 50000
#/MG/io/MCOpticalRun/KillAll 
/MG/io/MCOpticalRun/setWriteAllSteps
#/MG/io/MCOpticalRun/setWriteAllStepsInEventsThatDepositEnergy
#/MG/io/MCOpticalRun/setWriteAllSensitiveSteps



/MG/generator/select SPS
/gps/pos/type Point
/gps/pos/centre 580 0 0 mm
/gps/direction -1 0. 0.
/gps/particle gamma
/gps/ene/mono 1 MeV

#/MG/generator/confine volume
#/MG/generator/volume cryostat
#/MG/generator/select RDMiso
#/gun/energy 0 eV
#/grdm/ion 224 88 0
#/grdm/nucleusLimits 208 224 81 88
#generate particles in the liquid argon
#/MG/generator/select LGNDLiquidArgon
#/MG/generator/LGNDLiquidArgon/SetParticle beta
#/MG/generator/LGNDLiquidArgon/SetEnergy 1 MeV
#/tracking/verbose 2
/run/beamOn 100
#/MG/generator/select SPS
#/gps/particle opticalphoton
#/gps/ene/type Gauss
#/gps/ene/mono 9.6862 eV
#/gps/ene/sigma .2 eV
