# $Id: GNUmakefile,v 1.1.1.1 2004-11-08 17:53:42 gast Exp $
# --------------------------------------------------------------
# GNUmakefile for this module.      Akbar Mokhtarani, March-4-2004 
# --------------------------------------------------------------
SUBDIRS = src
 
.PHONY : all clean clean_libs lib

all:

lib:


clean:


clean_libs:


include