# specify the gdml file
/MG/geometry/GDML/sourceFile macros/Ge.gdml

# use low energy physics list
/MG/processes/lowenergy true
/MG/processes/realm DarkMatter

# set output schema and define file name
/MG/eventaction/rootschema G4Steps
/MG/eventaction/rootfilename dat/Ge_2MeV.root
/MG/eventaction/writeOutFrequency 1

# set verbose level
/MG/manager/mglog warning

# initialize MaGe
/run/initialize

/MG/generator/select SPS
/gps/particle gamma
/gps/energy 2 MeV
/gps/position 0 0 0
/gps/direction 0 0 1

/run/beamOn 1000
