# specify the gdml file you want to use
/MG/geometry/GDML/sourceFile /global/homes/g/gilliss/dev/mjswDev/MaGe_Val/MaGe/validation/GammaInteractions/macros/Cu.gdml

# use low energy physics list
/MG/processes/lowenergy true

# set output schema and define file name
/MG/eventaction/rootschema G4Steps
/MG/eventaction/rootfilename /global/homes/g/gilliss/dev/mjswDev/MaGe_Val/MaGe/validation/GammaInteractions/dat/Cu_20MeV.root
/MG/eventaction/writeOutFrequency 100

# initialize MaGe
/run/initialize

# draw the geometry
#/vis/open OGLSX
#/vis/viewer/set/viewpointVector 0 1 1
#/vis/viewer/set/background white
#/vis/viewer/set/defaultColour black
#/vis/viewer/set/viewpointThetaPhi 45
#/vis/drawVolume

# a simple simulation
/MG/generator/select SPS
/gps/particle gamma
/gps/energy 20 MeV
/gps/position 0 0 0
/gps/direction 0 0 1

# show the simulation
#/vis/scene/add/trajectories
/run/beamOn 1000
