# ===================================== #
# Draws detector with phase II geometry	#
# ===================================== # 

#
# Geometry setup 
#

/MG/geometry/detector GerdaArray
/MG/geometry/database false

/MG/geometry/detector/geometryfile geometry.dat
/MG/geometry/detector/matrixfile matrix_phase_ii.dat

#
# Geometry modifications 
#

#/MG/geometry/detector/CrystalZShiftScheme unshifted
/MG/geometry/detector/CrystalZShiftScheme center_between_top0_and_bottom2_on_common_zlevel
/MG/geometry/detector/CrystalZShiftScheme_UnshiftedColumn 18


#
# Initialize run 
#

/MG/processes/useNoHadPhysics true
/run/initialize

#
# visualization 
#

/vis/scene/create
#/vis/open OGLSX
/vis/open DAWNFILE
/vis/viewer/set/viewpointThetaPhi 50 270 deg
/vis/viewer/zoom 10.0

/vis/drawVolume 

/vis/viewer/flush 
 
