# ============================================= #
# Draws detector with standard geometry 	#
# ============================================= # 

#
# Geometry setup 
#

/MG/geometry/detector GerdaArray
/MG/geometry/database false

#
# Geometry modifications 
#

#
# Initialize run 
#

/run/initialize

#
# visualization
#


/vis/scene/create
/vis/open HepRepFile
/vis/viewer/set/viewpointThetaPhi 40 50 deg
/vis/viewer/zoom 3.0

/vis/drawVolume 

/vis/viewer/flush 
 


