# ====================== #
# Draws simple teststand #
# ====================== # 

#
# Geometry setup 
#

/MG/geometry/detector MunichTestStand
/MG/geometry/teststand/teststandtype simple
/MG/geometry/database false

#
# Geometry modifications 
#

#
# Initialize run 
#

/run/initialize

#
# visualization
#

/vis/scene/create
#/vis/open OGLSX
/vis/open DAWNFILE
/vis/viewer/set/viewpointThetaPhi 110 110 deg
/vis/viewer/zoom 50.0

/vis/drawVolume 

/vis/viewer/flush 

