#
# Example of using the Wang neutron generator.
# R. Henning, K. Hudek
# 9/2/2005
# Modified for SLACBD -> 17 Oct 2005
# M. Marino
#

# Management 
/MG/manager/mglog trace
/MG/manager/useInternalSeed 1

#/event/verbose 2
#/run/verbose 
#/tracking/verbose 2 

# Process List
/MG/geometry/database false
/MG/processes/realm CosmicRays
/MG/processes/lowenergy false
#/MG/processes/qgsp_hadron_list true
/MG/eventaction/reportingfrequency 1000

/MG/eventaction/writeOutFileDuringRun true
/MG/eventaction/writeOutFrequency 10000

# Configure Detector.
/MG/geometry/detector CERN_NA55
#/MG/geometry/SLACBD/setShieldThickness Thick 
/MG/geometry/WorldMaterial Vacuum

# ROOT output schema
/MG/eventaction/rootschema CERN_NA55 
/MG/eventaction/rootfilename temp.root 

# Select G4 Generator
/MG/generator/select G4gun 
/gun/number 1
/gun/particle mu-
/gun/position 0 0 0 cm
/gun/direction 0 0 1 
/gun/energy 190 GeV
/run/initialize
/run/beamOn 100000

