
/MG/manager/mjlog routine
/MG/geometry/detector clover
/MG/eventaction/rootschema LANLCloverNoPS
/MG/eventaction/rootfilename testTh.root
/MG/generator/select PNNLiso
/MG/generator/PNNL/init /auto/majorana1/MJ/database/generators/PNNL/Th232_DecayChain.dat
/MG/generator/PNNL/setsourceage 2.0
/MG/generator/PNNL/position 0.0 0.0 14.8
/MG/generator/PNNL/reportingfrequency 100
/run/initialize
/run/beamOn 2000
