/MG/manager/mglog routine
/MG/eventaction/reportingfrequency 100

#good random seed
#/MG/manager/seedWithUUID

#not random if used everytime!
/MG/manager/heprandomseed 1

/MG/processes/realm BBdecay
/MG/processes/lowenergy true


/MG/geometry/WorldMaterial Vacuum
/MG/geometry/detector TSMJDemModInTank


## Set parameters of Ton scale geometry here:
#set parameters of the tank (these are dimensions of the inside!!!)
/MG/geometry/TSCylinderShieldTank/height 6 m
/MG/geometry/TSCylinderShieldTank/radius 3 m
#Material can also be 'Water'
/MG/geometry/TSCylinderShieldTank/shieldmaterial LAB
#Material making the tank (only steel implemented now)
/MG/geometry/TSCylinderShieldTank/tankwallmaterial Steel
#thickness of tank wall
/MG/geometry/TSCylinderShieldTank/tankwallthickness 2 cm



#set parameters of lab module
#these set the size of the'lab space' (filled with air) where the tank sits
/MG/geometry/TSLabModuleBox/labheight 15 m
/MG/geometry/TSLabModuleBox/labwidth 15 m
/MG/geometry/TSLabModuleBox/lablength 30 m
#this sets the thickness of a layer of shotcrete around the 'lab' space
/MG/geometry/TSLabModuleBox/shotcretedepth 0.01 m
#this sets the amount of rock around the shotcrete
/MG/geometry/TSLabModuleBox/rockdepth 2.5 m
#sets the materials of the various components
/MG/geometry/TSLabModuleBox/rockmaterial Rock
/MG/geometry/TSLabModuleBox/shotcretematerial Rock
/MG/geometry/TSLabModuleBox/labspacematerial Air


#set parameters of the cryostat modules:
#set crystal diameter
/MG/geometry/TSMJDemModInTank/CrystalDiameter 77 mm

#set crystal height
/MG/geometry/TSMJDemModInTank/CrystalHeight 33 mm

#configuration, can be MJDemonstrator, 1Ring, 2Ring, 3Ring, 4Ring
/MG/geometry/TSMJDemModInTank/ModuleType 1Ring

#number of crystals per string, defaults to 10
/MG/geometry/TSMJDemModInTank/CrystalsPerString 5

#set type of crystal mount (MJDemonstrator, TS)
/MG/geometry/TSMJDemModInTank/CrystalAssemblyType TS

#the number of modules in the array (1-4)
/MG/geometry/TSMJDemModInTank/NumberOfModules 1


#set general parameters of the ton scale setup:
/MG/geometry/TSMJDemModInTank/TankIsActive true
/MG/geometry/TSMJDemModInTank/TankVerticalOffset 1 m

/MG/eventaction/rootschema MCRun
/MG/eventaction/rootfilename junk.root
/MG/io/MCRun/SetSensitiveIDLabelScheme askGeom
/MG/io/MCRun/setRunID 5054
/MG/io/MCRun/useTimeWindow true
/MG/io/MCRun/setTimeWindow 86400 second


################
###Parallel geometry, see event biasing below as well!
################
/MG/geometry/useParallelWorld true
/MG/geometry/TSMJDemModInTankPrallel/nRockParallelVolumes 25
/MG/geometry/TSMJDemModInTankPrallel/nShotcreteParallelVolumes 2
/MG/geometry/TSMJDemModInTankPrallel/nLabSpaceParallelVolumes 3
/MG/geometry/TSMJDemModInTankPrallel/nTankParallelVolumes 5
################


/run/initialize

################
###Different generators:
################
###208Tl decays
################
#/MG/generator/select RDMiso
#/gun/energy 0 eV
#/grdm/ion 208 81 0
#/MG/generator/confine volume
###/MG/generator/volume shieldtankphysical
##/MG/generator/volume shieldtankwallphysical
##/MG/generator/volume ShotCretePhysical
###/MG/generator/volume DetectorArray_001_CryostatPhysical
################
###Particle gun
################
#/MG/generator/select G4gun
#/gun/energy 2.0 MeV
#/gun/direction -1.0 0.0 0
#/gun/particle gamma
#/MG/generator/position 2.5 0 -3.5 m
################
###Cosmic rays
###See above settings to make the world volume very high
################
/MG/generator/select cosmicrays
/MG/generator/cosmicray/depth 4400.0 m
/MG/generator/cosmicray/height 9.5 m
/MG/generator/cosmicray/radius 7.5 m
################




################
####Event biasing, see Parallel worlds above (both should be un-commented)
################
/MG/geometry/EventBias/useImportanceSampling true
/MG/geometry/EventBias/setBiasedParticle gamma
/MG/geometry/EventBias/initializeVarRed
################


################
###Visualization
################
###Choose driver
################
#/vis/open OGLIXm
### Set camera angle for OGLIX driver
#/vis/viewer/set/viewpointThetaPhi 90 90
#/vis/open DAWNFILE
/vis/open HepRepFile
#
### Add world volume
/vis/drawVolume worlds
/vis/viewer/flush
/vis/scene/add/trajectories
/vis/scene/add/hits
/vis/scene/endOfEventAction accumulate

################
###Run events!
################

/run/beamOn 1






