//---------------------------------------------------------------------------//
//bb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nu//
//                                                                           //
//                                                                           //
//                         MaGe Simulation                                   //
//                                                                           //
//      This code implementation is the intellectual property of the         //
//      MAJORANA and Gerda Collaborations. It is based on Geant4, an         //
//      intellectual property of the RD44 GEANT4 collaboration.              //
//                                                                           //
//                        *********************                              //
//                                                                           //
//    Neither the authors of this software system, nor their employing       //
//    institutes, nor the agencies providing financial support for this      //
//    work  make  any representation or  warranty, express or implied,       //
//    regarding this software system or assume any liability for its use.    //
//    By copying, distributing or modifying the Program (or any work based   //
//    on on the Program) you indicate your acceptance of this statement,     //
//    and all its terms.                                                     //
//                                                                           //
//bb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nubb0nu//
//---------------------------------------------------------------------------//
/**                                                            
 * $Id: MGGeneratorGeneralSurfaceSampler.hh,v 1.1 2006-01-24 02:55:47 jasondet Exp $
 *      
 * CLASS DECLARATION:  MGGeneratorGeneralSurfaceSampler.hh
 *
 *---------------------------------------------------------------------------//
 *
 * DESCRIPTION: 
 *
 */ 
// Begin description of class here
/**
 *
 * Generate Beam of Neutrons as would be generated by high
 * energy muons in an underground facility.
 * Currently the beam is simulated with an equation by Wnag, et. al.
 * Particles are then generated parallel to 
 * the z-axis.
 *
 * MGGeneratorTUNLFEL.* is being used as an example.
 *
 */
// End class description
//
/**  
 * SPECIAL NOTES:
 *
 */
// 
// --------------------------------------------------------------------------//
/** 
 * AUTHOR: J. Detwiler
 * CONTACT: 
 * FIRST SUBMISSION: 
 * 
 * REVISION:
 * 
 */
// --------------------------------------------------------------------------//

#ifndef _MGGENERATORGENERALSURFACESAMPLER_HH
#define _MGGENERATORGENERALSURFACESAMPLER_HH

#include "generators/MGVGenerator.hh"
#include "G4ParticleGun.hh"

class MGGeneratorGeneralSurfaceSamplerMessenger;

class MGGeneratorGeneralSurfaceSampler : public MGVGenerator
{
  public:
    MGGeneratorGeneralSurfaceSampler();
    virtual ~MGGeneratorGeneralSurfaceSampler() {}

    virtual void GeneratePrimaryVertex(G4Event* event);
    virtual void SetParticlePosition(G4ThreeVector vec)
      { SetOrigin(vec); }

    virtual void SetOrigin(const G4ThreeVector& origin);
    virtual void SetBoundingRadius(G4double radius);

  protected:
    MGGeneratorGeneralSurfaceSamplerMessenger* fMessenger;
    G4ThreeVector fOrigin;
    G4double fBoundingRadius;
    G4ParticleGun fParticleGun;
};

#endif
